
name: Build, Test and Publish Docker (Dev)


on:
  push:
    branches:
      - feature/**

jobs:

  build-test-publish:
    name: Build, Test and Publish Docker Image (Dev)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore src/zeferini-person-api-dotnet.slnx
      - name: Build
        run: dotnet build src/zeferini-person-api-dotnet.slnx --no-restore
      - name: Test
        run: dotnet test src/zeferini-person-api-dotnet.slnx --no-build --verbosity normal
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DEV_DOCKERHUB_USERNAME }}
          password: ${{ secrets.DEV_DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t zeferinidotdev/zeferini-person-api-dotnet:dev -f Dockerfile .
      - name: Push Docker image
        run: docker push zeferinidotdev/zeferini-person-api-dotnet:dev

