
name: Create PR from feature to develop

on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

jobs:
  create-pr-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - name: Listar branches disponíveis
        run: git branch -a && git status
      - name: Debug branch e token
        run: |
          echo "Branch: ${{ github.head_ref || github.ref_name }}"
          echo "Usuário do token: $(gh api user --jq .login)" || echo "GH CLI não disponível, verifique permissões do token."
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
      - name: Create Pull Request to develop
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          base: develop
          branch: ${{ github.head_ref || github.ref_name }}
          title: 'Merge feature ${{ github.head_ref || github.ref_name }} into develop'
          body: 'PR automática criada pelo CI após build, test e publish da imagem dev.'
          draft: false
