name: Trigger PR Feature to Develop

on:
  push:
    branches:
      - 'feature/**'

jobs:
  call-create-pr:
    uses: ./.github/workflows/pr-feature-to-develop.yml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
